extensions:
  developer:
    enabled: false
    type: builtin
    name: developer
  analyze:
    enabled: false
    type: builtin
    name: analyze
  todo:
    enabled: false
    type: builtin
    name: todo
  xcode:
    enabled: false
    type: stdio
    name: xcode
    cmd: xcrun
    args:
    - mcpbridge
    envs: {}
    env_keys: []
    timeout: 300
  context7:
    enabled: false
    type: stdio
    name: context7
    cmd: npx
    args:
    - -y
    - '@upstash/context7-mcp'
    envs: {}
    env_keys: []
    timeout: 300
  summarize:
    enabled: false
    type: builtin
    name: summarize
  summon:
    enabled: false
    type: builtin
    name: summon
  autovisualiser:
    enabled: false
    type: builtin
    name: autovisualiser
  tom:
    enabled: false
    type: builtin
    name: tom
  extensionmanager:
    enabled: false
    type: builtin
    name: extensionmanager
  apps:
    enabled: false
    type: builtin
    name: apps
  chatrecall:
    enabled: false
    type: builtin
    name: chatrecall
  code_execution:
    enabled: false
    type: builtin
    name: code_execution
  computercontroller:
    enabled: false
    type: builtin
    name: computercontroller
  memory:
    enabled: false
    type: builtin
    name: memory
  tutorial:
    enabled: false
    type: builtin
    name: tutorial
  chromedevtools:
    enabled: false
    type: builtin
    name: chromedevtools
  orchestrator:
    enabled: false
    type: builtin
    name: orchestrator
